# Shubham Kumar Chaturvedi(DeepLearning assigment no: 12)

Q1: How does unsqueeze help us to solve certain broadcasting problems?

ANS: unsqueeze is a method to change the tensor dimensions, such that operations such as tensor multiplication can be possible. This basically alters the dimension to produce a tensor that has a different dimension.

Q2: How can we use indexing to do the same operation as unsqueeze?

ANS: Import the required library. In all the following Python examples, the required Python library is torch. Make sure you have already installed it.

Create a tensor and print it.

Compute torch.squeeze(input). It squeezes (removes) the size 1 and returns a tensor with all other dimensions of the input tensor.

Compute torch.unsqueeze(input, dim). It inserts a new dimension of size 1 at the given dim and returns the tensor.

Print the squeezed and/or unsqueezed tensor.

Q3: How do we show the actual contents of the memory used for a tensor?

ANS: For GPUs, TensorFlow will allocate all the memory by default, unless changed with tf.config.experimental.set_memory_growth. This function only returns the memory that TensorFlow is actually using, not the memory that TensorFlow has allocated on the GPU.

Q4: Do broadcasting and expand_as result in increased memory use? Why or why not?

ANS: Broadcasting should not increase the memory usage, but you would of course need to store the result. 

Q5: Implement matmul using Einstein summation.

ANS: The einsum() method evaluates the Einstein summation convention on the operands. Using the Einstein summation convention, many common multi-dimensional, linear algebraic array operations can be represented in a simple fashion. In implicit mode einsum computes these values.

In explicit mode, einsum provides further flexibility to compute other array operations that might not be considered classical Einstein summation operations, by disabling, or forcing summation over specified subscript labels.

In [1]:
import numpy as np

# Creating two numpy One-Dimensional array using the array() method
arr1 = np.arange(25).reshape(5,5)
arr2 = np.arange(5)

# Display the arrays
print("Array1...\n",arr1)
print("\nArray2...\n",arr2)

# Check the Dimensions of both the arrays
print("\nDimensions of Array1...\n",arr1.ndim)
print("\nDimensions of Array2...\n",arr2.ndim)

# Check the Shape of both the arrays
print("\nShape of Array1...\n",arr1.shape)
print("\nShape of Array2...\n",arr2.shape)

# For Matrix Vector multiplication with Einstein summation convention, use the numpy.einsum() method in Python.
print("\nResult (Matrix Vector multiplication)...\n",np.einsum('ij,j', arr1, arr2))

Array1...
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Array2...
 [0 1 2 3 4]

Dimensions of Array1...
 2

Dimensions of Array2...
 1

Shape of Array1...
 (5, 5)

Shape of Array2...
 (5,)

Result (Matrix Vector multiplication)...
 [ 30  80 130 180 230]


Q6: What are the three rules of Einstein summation notation? Why?

ANS: The “rules” of summation convention are:

 Each index can appear at most twice in any term.
 
  Repeated indices are implicitly summed over. 
  
  Each term must contain identical non-repeated indices.

   Einstein summation convention or Einstein summation notation) is a notational convention that implies summation over a set of indexed terms in a formula, thus achieving brevity.

Q7: Why do we need to store some of the activations calculated for intermediate layers in the
forward pass?

ANS: we need to store all intermediate activations during training because they are needed to compute gradients during back-propagation: (5)-(8) involve not just the values of the incoming gradient, but also the values of the activations themselves.

Q8: How can weight initialization help avoid this problem?

ANS:  building a neural network, it's important to initialize weights beforehand. Weights can be thought of as the amount of influence the input has on the output. With weight initialization, we set the weights to random values to prevent the layer outputs or gradients from vanishing or exploding.

